#!/bin/bash

function printc {
  RED='\033[0;31m'
  NC='\033[0m' # No Color
  echo -e '>>> '${RED}"$1"${NC}
}

printc 'vagrant up'
vagrant up

printc 'vagrant provision'
vagrant provision

printc 'vagrant reload'
vagrant reload

printc 'vagrant ssh'
vagrant ssh
