#!/bin/bash

function printc {
  RED='\033[0;31m'
  NC='\033[0m' # No Color
  echo -e '>>> '${RED}"$1"${NC}
}

case "$1" in

"--help" )
  echo Ayuda en construcción
  ;;

"h" )
printc 'vagrant halt'
vagrant halt  
  ;;

"r" )
printc 'vagrant reload'
vagrant reload
printc 'vagrant ssh'
vagrant ssh
  ;;

*)
printc 'vagrant up'
vagrant up
printc 'vagrant ssh'
vagrant ssh
  ;;

esac
