#!/bin/bash

function printc {
  RED='\033[0;31m'
  NC='\033[0m' # No Color
  echo -e '>>> '${RED}"$1"${NC}
}

case "$1" in

"--help" )
  echo Ayuda en construcción
  ;;

*)
  printc 'gulp'
  gulp
  ;;

esac
